#!/bin/sh
set -e

hookDir=$(dirname "$0")
WORKDIR=$(git rev-parse --show-toplevel)

cd $WORKDIR

cargo fmt --all -- --check
cargo clippy

cargo build --tests --bins --examples --color=always

cd "${WORKDIR}/integration_test"
./run_integration_test.sh
