#!/bin/sh
set -e

hookDir=$(dirname "$0")
WORKDIR=$(git rev-parse --show-toplevel)

cd $WORKDIR
set -o allexport
[[ -f .env ]] && source .env
set +o allexport

cargo fmt --all -- --check
cargo clippy

cargo build
cargo test --verbose
