#!/bin/sh
set -e

hookDir=$(dirname "$0")
WORKDIR=$(git rev-parse --show-toplevel)

cd $WORKDIR

#gem install travis
#travis lint .travis.yml --exit-code

cargo fmt --all -- --check
cargo clippy

cargo build --tests --bins --examples --color=always

[[ ! -f .env ]] && cp .env_default .env
set -o allexport
[[ -f .env ]] && source .env
set +o allexport

cd "${WORKDIR}/integration_test"
./run_integration_test.sh
